# Generated by Django 5.1.7 on 2025-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('cook_time', models.IntegerField(help_text='Tiempo en minutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
